export const SHIPMENT_ACTION_TYPES = {
    FETCH_SHIPMENTS_SUCCESS: "FETCH_SHIPMENTS_SUCCESS",
    FETCH_SHIPMENTS_FAILURE: "FETCH_SHIPMENTS_FAILURE",

    SHIPMENT_NAME_UPDATE_SUCCESS: "SHIPMENT_NAME_UPDATE_SUCCESS",
    SHIPMENT_NAME_UPDATE_FAILURE: "SHIPMENT_NAME_UPDATE_FAILURE"
}